In [1]:
import os
import pandas as pd
import numpy as np
os.chdir("C:/Users/Guido vd Heijden/Documents/School/Semester 3/Advanced Machine Learning/Project NotGoingToWin")
data = pd.read_csv('all/train.csv')
testdata = pd.read_csv('all/test.csv')

In [2]:
train = np.array(data)
test = np.array(testdata)

train_size = train.shape[0]
test_size = test.shape[0]

## Removing outliers
Remove all rows in the training data with target value -33.21928095.

In [190]:
data = data[data.target != -33.21928095]

In [191]:
data.to_csv('all/train_without_outliers.csv', index = False)

## Adding (useable) feature for first_active_month
Here the first_active_month is transformed by multiplying the years by 12 and adding the months. The "magic" number 24143 is the very first month a card was recorded to be first active: 2011-11, November 2011, so that is substracted to let the feature's minimum be 0.

In [ ]:
# for training set
train_fam_feature = np.zeros(train_size)

for i in range(train_size):
    feature_row = train[i,0].split('-')
    train_fam_feature[i] = int(feature_row[0])*12 + int(feature_row[1]) - 24143
    
# for test set
test_fam_feature = np.zeros(test_size)

for i in range(test_size):
    
    if type(test[i,0]) != float: #if-statement, because missing value
        feature_row = test[i,0].split('-')
    test_fam_feature[i] = int(feature_row[0])*12 + int(feature_row[1]) - 24143

In [ ]:
# inserting the feature in training data
data.insert(5,"fam_feature",train_fam_feature)

# inserting the feature in test data
testdata.insert(5,"fam_feature",test_fam_feature)

In [ ]:
# run to see data as pandas dataframe
data

In [ ]:
# run to see testdata as pandas dataframe
testdata

## Historical transactions - feature for city_id & state_id
A feature will be extracted for the city_id. This feature should represent how locally the customer buys. The formula for this is: (_transactions at most visited city_ / _total transactions_) * (_transactions at most visited state_ / _total transactions_).
The feature is a value between 0 and 1. If the feature returns 1, then the customer buys only locally. If the feature returns a number closer to 0, then the customer buys frequently outside his city and/or state.

In [3]:
historical_transactions = pd.read_csv('all/historical_transactions.csv')

In [122]:
historical_transactions

29112361

In [147]:
MVC = 0
MVS = 0
transactions = 0
start = 0

for i in range(100):
    MVC = historical_transactions.loc[historical_transactions['card_id'] == train[i+start,1]].city_id.value_counts().max()
    MVS = historical_transactions.loc[historical_transactions['card_id'] == train[i+start,1]].state_id.value_counts().max()
    transactions = historical_transactions.loc[historical_transactions['card_id'] == train[i+start,1]].city_id.count()
    print( (MVC*MVS)/transactions**2 )

0.9428402366863905
0.7289877551020408
0.8226068144943213
0.45606341710237813
0.5653230821414439
0.8539944903581267
0.7137573964497042
0.5289256198347108
0.5377777777777778
0.8128279426736628
0.9288978637474758
1.0
0.6574141709276844
0.54
0.613491124260355
0.8147368421052632
0.46003780718336484
1.0
0.51440329218107
0.35294399302845597
0.12555555555555556
0.8622448979591837
1.0
0.41758494031221305
0.7443388009870808
1.0
0.7447916666666666
0.68
0.8176859504132231
0.8533113413890782
0.4444444444444444
0.916058394160584
0.24685185185185185
0.7828282828282829
0.9347826086956522
0.6541810139693738
1.0
0.5169230769230769
0.4074074074074074
0.2916
0.8858131487889274
0.5849379329031821
0.177734375
0.144
0.1388888888888889
0.6618106139438086
0.9138965835641736
0.8333333333333334
0.396
0.8163265306122449
0.874641446343982
0.875
0.7256944444444444
0.9848484848484849
0.7974683544303798
0.76
0.9523809523809523
0.3855994152046784
0.4604331528529779
0.7458888888888889
0.5510135887725551
0.984375
0.2869897959183674
0.7104081632653061
0.5565862708719852
0.3561394380853278
0.5625
0.4962192816635161
0.4302231471846456
0.32783207819259735
0.38761416796613946
0.5950413223140496
0.7257455469800512
0.47231736233956867
1.0
0.6777645659928656
0.6696428571428571
0.4306640625
0.42
0.6521739130434783
0.655328798185941
0.5604338842975206
0.4444444444444444
0.9085992428339643
0.6486194315571371
0.3525390625
0.9622641509433962
1.0
0.25
0.502809917355372
0.9541284403669725
0.6026296566837107
1.0
0.4425947945567446
0.46636363636363637
0.8639760559190958
0.4722222222222222
0.65625
1.0
0.851291745431632

In [148]:
MVC = 0
MVS = 0
transactions = 0
start = 0

for i in range(100):
#     MVC = historical_transactions.loc[historical_transactions['card_id'] == train[i+start,1]].city_id.value_counts().max()
#     MVS = historical_transactions.loc[historical_transactions['card_id'] == train[i+start,1]].state_id.value_counts().max()
    transactions = historical_transactions.loc[historical_transactions['card_id'] == train[i+start,1]].city_id.count()
#     print( (MVC*MVS)/transactions**2 )
    print (transactions)

260
350
43
77
133
33
260
22
15
113
97
19
37
20
65
190
115
82
27
457
180
28
16
132
166
135
96
20
110
167
48
274
180
66
46
189
44
325
36
100
34
243
32
25
12
62
114
18
100
21
247
8
48
132
79
25
21
228
98
300
134
64
28
140
77
124
8
46
93
79
67
55
233
163
12
58
28
32
50
23
63
44
21
86
149
96
53
5
22
55
109
37
38
87
110
328
36
32
12
207

In [145]:
%%timeit -n 3 -r 3
100/133*100/133

243 ns ± 99.3 ns per loop (mean ± std. dev. of 3 runs, 3 loops each)

In [121]:
historical_transactions.loc[historical_transactions['card_id'] == 'C_ID_904bca0f4b']

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id
4878813,Y,C_ID_904bca0f4b,333,N,0,A,80,M_ID_98b342c0e3,0,-0.296112,2018-02-08 19:27:43,1.0,9,37
4878814,Y,C_ID_904bca0f4b,69,N,0,A,511,M_ID_00a6ca8a8a,-13,-0.709342,2017-01-18 14:46:20,1.0,9,7
4878815,Y,C_ID_904bca0f4b,333,N,0,A,480,M_ID_671c20a026,-2,-0.610647,2017-12-26 12:53:39,1.0,9,24
4878816,Y,C_ID_904bca0f4b,333,N,0,A,367,M_ID_dfcf66c65e,-6,-0.533531,2017-08-07 10:28:46,1.0,9,16
4878817,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_c57af8d2e4,-3,-0.703677,2017-11-10 15:33:30,1.0,9,33
4878818,Y,C_ID_904bca0f4b,333,N,0,A,367,M_ID_dfcf66c65e,-2,-0.659754,2017-12-07 07:50:18,1.0,9,16
4878819,Y,C_ID_904bca0f4b,333,N,0,A,360,M_ID_a3cd2b2e62,-13,-0.718357,2017-01-01 11:44:22,1.0,9,34
4878820,Y,C_ID_904bca0f4b,242,N,0,A,480,M_ID_671c20a026,-11,-0.715863,2017-03-31 19:22:53,1.0,9,24
4878821,Y,C_ID_904bca0f4b,242,N,0,A,480,M_ID_671c20a026,-13,-0.697290,2017-01-14 14:55:37,1.0,9,24
4878822,Y,C_ID_904bca0f4b,333,N,0,A,222,M_ID_de40fbd87c,-11,-0.742099,2017-03-06 18:21:10,1.0,9,21
4878823,Y,C_ID_904bca0f4b,69,N,0,A,879,M_ID_00a6ca8a8a,-5,-0.706336,2017-09-15 15:27:38,1.0,9,29
4878824,Y,C_ID_904bca0f4b,333,N,0,A,367,M_ID_dfcf66c65e,0,-0.686802,2018-02-01 14:06:24,1.0,9,16
4878825,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_c57af8d2e4,-12,-0.580414,2017-02-11 09:24:46,1.0,9,33
4878826,Y,C_ID_904bca0f4b,242,N,0,A,480,M_ID_671c20a026,-7,-0.678733,2017-07-31 15:52:57,1.0,9,24
4878827,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_c57af8d2e4,-12,-0.466378,2017-02-24 12:13:40,1.0,9,33
4878828,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_b98db225f5,-6,-0.679319,2017-08-22 12:06:59,1.0,9,33
4878829,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_b98db225f5,-2,-0.741168,2017-12-13 14:03:16,1.0,9,33
4878830,Y,C_ID_904bca0f4b,333,N,0,A,80,M_ID_98b342c0e3,0,-0.446378,2018-02-21 13:44:09,1.0,9,37
4878831,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_b98db225f5,-9,-0.713624,2017-05-16 16:27:51,1.0,9,33
4878832,Y,C_ID_904bca0f4b,333,N,0,A,671,M_ID_d322b16e75,-2,-0.719860,2017-12-18 07:27:43,1.0,9,7
4878833,Y,C_ID_904bca0f4b,333,N,0,A,367,M_ID_dfcf66c65e,-2,-0.739395,2017-12-05 12:39:26,1.0,9,16
4878834,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_b98db225f5,-11,-0.714721,2017-03-17 17:52:45,1.0,9,33
4878835,Y,C_ID_904bca0f4b,333,N,0,A,511,M_ID_98995b54fb,-11,-0.589129,2017-03-22 14:08:47,1.0,9,7
4878836,Y,C_ID_904bca0f4b,333,N,0,A,307,M_ID_9249713597,-6,-0.716855,2017-08-14 14:14:35,1.0,9,19
4878837,Y,C_ID_904bca0f4b,333,N,0,A,480,M_ID_671c20a026,-2,-0.739966,2017-12-06 12:25:29,1.0,9,24
4878838,Y,C_ID_904bca0f4b,242,N,0,A,480,M_ID_671c20a026,-4,-0.716900,2017-10-09 20:33:21,1.0,9,24
4878839,N,C_ID_904bca0f4b,333,N,0,A,278,M_ID_d855771cd9,-2,-0.647733,2017-12-23 19:34:03,1.0,9,37
4878840,Y,C_ID_904bca0f4b,333,N,0,A,480,M_ID_671c20a026,-1,-0.731250,2018-01-20 15:10:57,1.0,9,24
4878841,Y,C_ID_904bca0f4b,333,N,0,A,480,M_ID_671c20a026,-2,-0.658702,2017-12-17 08:28:58,1.0,9,24
4878842,Y,C_ID_904bca0f4b,333,N,0,A,222,M_ID_de40fbd87c,-6,-0.714601,2017-08-31 13:25:07,1.0,9,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4878969,Y,C_ID_904bca0f4b,333,N,0,A,367,M_ID_dfcf66c65e,0,-0.724368,2018-02-21 07:10:12,1.0,9,16
4878970,Y,C_ID_904bca0f4b,242,N,0,A,480,M_ID_671c20a026,-6,-0.664743,2017-08-13 09:17:24,1.0,9,24
4878971,Y,C_ID_904bca0f4b,333,N,0,A,80,M_ID_98b342c0e3,-7,-0.671775,2017-07-21 22:25:54,1.0,9,37
4878972,Y,C_ID_904bca0f4b,333,N,0,A,480,M_ID_671c20a026,-2,-0.690919,2017-12-05 12:33:50,1.0,9,24
4878973,Y,C_ID_904bca0f4b,242,N,0,A,480,M_ID_671c20a026,-13,-0.696208,2017-01-18 14:42:49,1.0,9,24
4878974,Y,C_ID_904bca0f4b,242,N,0,A,480,M_ID_671c20a026,-8,-0.737126,2017-06-20 09:11:26,1.0,9,24
4878975,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_c57af8d2e4,-11,-0.727178,2017-03-20 18:03:49,1.0,9,33
4878976,Y,C_ID_904bca0f4b,333,N,0,A,480,M_ID_671c20a026,-3,-0.669596,2017-11-14 00:00:00,1.0,9,24
4878977,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_c57af8d2e4,-1,-0.444589,2018-01-27 11:52:50,1.0,9,33
4878978,Y,C_ID_904bca0f4b,242,N,0,A,480,M_ID_671c20a026,-13,-0.614825,2017-01-21 10:36:47,1.0,9,24
4878979,Y,C_ID_904bca0f4b,333,N,0,A,363,M_ID_8b1d54a2e1,-2,-0.716825,2017-12-26 11:44:39,1.0,9,18
4878980,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_c57af8d2e4,-5,-0.271048,2017-09-08 12:25:38,1.0,9,33
4878981,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_b98db225f5,-7,-0.719965,2017-07-25 15:50:41,1.0,9,33
4878982,Y,C_ID_904bca0f4b,333,N,0,A,489,M_ID_dfcf66c65e,-12,-0.679288,2017-02-11 09:28:35,1.0,9,16
4878983,Y,C_ID_904bca0f4b,333,N,0,A,783,M_ID_b86f065dde,-4,-0.664262,2017-10-30 00:00:00,1.0,9,19
4878984,Y,C_ID_904bca0f4b,333,N,0,A,222,M_ID_de40fbd87c,-13,-0.729177,2017-01-26 14:22:40,1.0,9,21
4878985,Y,C_ID_904bca0f4b,333,N,0,A,367,M_ID_dfcf66c65e,-8,-0.731881,2017-06-03 09:51:46,1.0,9,16
4878986,Y,C_ID_904bca0f4b,333,N,0,A,367,M_ID_dfcf66c65e,-8,-0.682294,2017-06-29 13:35:40,1.0,9,16
4878987,Y,C_ID_904bca0f4b,333,N,0,A,222,M_ID_de40fbd87c,-12,-0.707839,2017-02-06 13:59:02,1.0,9,21
4878988,Y,C_ID_904bca0f4b,69,N,0,A,879,M_ID_00a6ca8a8a,-3,-0.689807,2017-11-14 13:37:01,1.0,9,29
4878989,Y,C_ID_904bca0f4b,69,N,0,A,511,M_ID_00a6ca8a8a,-11,-0.649987,2017-03-09 14:13:33,1.0,9,7
4878990,Y,C_ID_904bca0f4b,333,N,0,A,278,M_ID_d855771cd9,-2,-0.647733,2017-12-23 19:41:06,1.0,9,37
4878991,Y,C_ID_904bca0f4b,333,N,0,A,705,M_ID_c57af8d2e4,-4,-0.673007,2017-10-24 15:29:11,1.0,9,33
4878992,N,C_ID_904bca0f4b,333,N,0,A,278,M_ID_d855771cd9,-2,-0.647733,2017-12-23 19:32:29,1.0,9,37
4878993,Y,C_ID_904bca0f4b,333,N,0,A,367,M_ID_dfcf66c65e,-7,-0.533531,2017-07-12 17:04:33,1.0,9,16
4878994,Y,C_ID_904bca0f4b,69,N,0,A,511,M_ID_00a6ca8a8a,-11,-0.737892,2017-03-09 20:48:52,1.0,9,7
4878995,Y,C_ID_904bca0f4b,333,N,0,A,367,M_ID_dfcf66c65e,-9,-0.728876,2017-05-06 13:29:57,1.0,9,16
4878996,Y,C_ID_904bca0f4b,242,N,0,A,480,M_ID_671c20a026,-12,-0.650107,2017-02-18 16:48:18,1.0,9,24
4878997,Y,C_ID_904bca0f4b,242,N,0,A,480,M_ID_671c20a026,-7,-0.731791,2017-07-01 14:55:23,1.0,9,24
4878998,Y,C_ID_904bca0f4b,333,N,0,A,80,M_ID_98b342c0e3,-4,-0.521510,2017-10-13 00:00:00,1.0,9,37

In [120]:
historical_transactions.loc[historical_transactions['card_id'] == 'C_ID_92a2005557']

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id
12454872,Y,C_ID_92a2005557,69,N,0,A,195,M_ID_cc72dac895,-3,-0.506033,2017-11-25 16:37:11,1.0,9,34
12454873,Y,C_ID_92a2005557,69,N,0,A,278,M_ID_c9c0f1cb3f,-7,-0.722114,2017-07-16 12:21:00,1.0,9,37
12454874,Y,C_ID_92a2005557,69,N,0,A,683,M_ID_36f9e41993,-6,-0.726171,2017-08-10 21:01:16,1.0,9,34
12454875,Y,C_ID_92a2005557,69,N,0,A,309,M_ID_b790230ee9,-2,-0.610167,2017-12-15 12:06:58,1.0,9,21
12454876,Y,C_ID_92a2005557,69,N,0,A,278,M_ID_ab67f6c982,-7,-0.307232,2017-07-08 15:13:18,1.0,9,37
12454877,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_b3c49066d8,-6,-0.662158,2017-08-13 13:43:07,1.0,9,34
12454878,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_b3c49066d8,-1,-0.665614,2018-01-27 06:44:29,1.0,9,34
12454879,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_b3c49066d8,-7,-0.727944,2017-07-01 09:02:20,1.0,9,34
12454880,Y,C_ID_92a2005557,69,N,0,A,80,M_ID_c124c4467a,-5,-0.620986,2017-09-02 23:05:56,1.0,9,37
12454881,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_1a81c358a3,-7,-0.722114,2017-07-27 08:17:48,1.0,9,34
12454882,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_b3c49066d8,0,-0.595230,2018-02-25 09:25:39,1.0,9,34
12454883,Y,C_ID_92a2005557,69,N,0,A,130,M_ID_166984dc8f,-2,-0.491457,2017-12-20 11:55:05,1.0,9,41
12454884,Y,C_ID_92a2005557,69,N,0,A,454,M_ID_8e24779ad0,-5,-0.686802,2017-09-30 20:06:30,1.0,9,39
12454885,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_1a81c358a3,-7,-0.700356,2017-07-07 13:58:08,1.0,9,34
12454886,Y,C_ID_92a2005557,69,N,0,A,637,M_ID_800c9d11e3,-7,-0.731881,2017-07-12 15:20:45,1.0,9,37
12454887,Y,C_ID_92a2005557,69,N,0,A,526,M_ID_03bb6f5a3b,-2,-0.656749,2017-12-20 18:28:09,1.0,9,25
12454888,Y,C_ID_92a2005557,69,N,0,A,108,M_ID_0888bdef7e,-5,-0.494883,2017-09-07 16:30:10,1.0,9,34
12454889,Y,C_ID_92a2005557,69,N,0,A,80,M_ID_c124c4467a,-6,-0.599949,2017-08-26 21:51:48,1.0,9,37
12454890,Y,C_ID_92a2005557,69,N,0,A,884,M_ID_9122ebdd02,-5,-0.638717,2017-09-17 19:48:49,1.0,9,27
12454891,Y,C_ID_92a2005557,231,N,0,A,454,M_ID_4b30e99bda,-4,-0.728876,2017-10-09 18:42:12,1.0,9,39
12454892,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_1a81c358a3,-7,-0.726171,2017-07-26 08:08:11,1.0,9,34
12454893,Y,C_ID_92a2005557,69,N,0,A,454,M_ID_6b718b517f,-4,-0.709342,2017-10-04 18:52:58,1.0,9,39
12454894,Y,C_ID_92a2005557,69,N,0,A,561,M_ID_50f575c681,-5,-0.677681,2017-09-16 01:30:25,1.0,9,7
12454895,Y,C_ID_92a2005557,69,N,0,A,478,M_ID_de54dcf09d,-4,-0.580114,2017-10-05 18:48:46,1.0,9,7
12454896,Y,C_ID_92a2005557,69,N,0,A,454,M_ID_eb154b339f,-2,-0.728876,2017-12-14 09:56:57,1.0,9,39
12454897,Y,C_ID_92a2005557,69,N,0,A,278,M_ID_0ef7af562d,-2,-0.362109,2017-12-11 13:40:13,1.0,9,37
12454898,Y,C_ID_92a2005557,69,N,0,A,454,M_ID_6b718b517f,-1,-0.712347,2018-01-09 10:06:54,1.0,9,39
12454899,Y,C_ID_92a2005557,69,N,0,A,879,M_ID_00a6ca8a8a,0,-0.707899,2018-02-17 09:39:17,1.0,9,29
12454900,Y,C_ID_92a2005557,69,N,0,A,454,M_ID_800c9d11e3,-2,-0.722865,2017-12-13 16:01:01,1.0,9,39
12454901,Y,C_ID_92a2005557,69,N,0,A,195,M_ID_cc72dac895,-1,-0.589580,2018-01-13 14:23:54,1.0,9,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12455102,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_b3c49066d8,-1,-0.733429,2018-01-23 07:13:10,1.0,9,34
12455103,Y,C_ID_92a2005557,69,N,0,A,195,M_ID_27ef0c464c,-7,-0.720010,2017-07-06 20:58:32,1.0,9,34
12455104,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_1a81c358a3,-7,-0.675457,2017-07-19 13:48:00,1.0,9,34
12455105,N,C_ID_92a2005557,69,N,1,B,792,M_ID_03bb6f5a3b,-4,-0.653743,2017-10-04 22:31:01,1.0,9,9
12455106,Y,C_ID_92a2005557,69,N,0,A,195,M_ID_cc72dac895,-5,-0.611218,2017-09-02 17:59:20,1.0,9,34
12455107,Y,C_ID_92a2005557,69,N,0,A,705,NaN,0,-0.697471,2018-02-18 10:11:26,1.0,9,33
12455108,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_b3c49066d8,0,-0.724593,2018-02-18 05:55:03,1.0,9,34
12455109,Y,C_ID_92a2005557,69,N,0,A,367,M_ID_820c7b73c8,-2,-0.712167,2017-12-01 22:50:13,1.0,9,16
12455110,Y,C_ID_92a2005557,69,N,0,A,80,M_ID_5ba019a379,0,-0.718658,2018-02-04 17:05:55,1.0,9,37
12455111,Y,C_ID_92a2005557,69,N,0,A,80,M_ID_5ba019a379,-5,-0.665765,2017-09-12 17:04:54,1.0,9,37
12455112,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_1a81c358a3,-7,-0.712888,2017-07-27 14:23:56,1.0,9,34
12455113,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_326998c1aa,-5,-0.512795,2017-09-16 21:18:50,1.0,9,34
12455114,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_b3c49066d8,0,-0.731385,2018-02-08 07:33:00,1.0,9,34
12455115,Y,C_ID_92a2005557,69,N,0,A,420,M_ID_bd2f7edfa0,0,-0.724368,2018-02-02 08:47:57,1.0,9,31
12455116,Y,C_ID_92a2005557,69,N,0,A,80,M_ID_8f7abb829d,-3,-0.629400,2017-11-27 16:27:14,1.0,9,37
12455117,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_1a81c358a3,-7,-0.702489,2017-07-13 14:57:36,1.0,9,34
12455118,Y,C_ID_92a2005557,69,N,0,A,367,M_ID_820c7b73c8,-3,-0.560008,2017-11-25 19:49:01,1.0,9,16
12455119,Y,C_ID_92a2005557,69,N,0,A,454,M_ID_eb154b339f,-7,-0.724368,2017-07-04 14:05:19,1.0,9,39
12455120,Y,C_ID_92a2005557,181,N,0,A,367,M_ID_baffe72349,-1,-0.679559,2018-01-05 11:01:06,5.0,5,16
12455121,Y,C_ID_92a2005557,69,N,0,A,278,M_ID_ed31e01703,-1,-0.231453,2018-01-11 20:34:12,1.0,9,37
12455122,Y,C_ID_92a2005557,69,N,0,A,606,M_ID_cd2c0b07e9,-4,-0.718357,2017-10-17 13:21:44,1.0,9,17
12455123,Y,C_ID_92a2005557,69,N,0,A,454,M_ID_800c9d11e3,-1,-0.724368,2018-01-23 13:30:58,1.0,9,39
12455124,Y,C_ID_92a2005557,69,N,0,A,779,M_ID_855512f895,-2,-0.611819,2017-12-30 14:55:23,1.0,9,27
12455125,Y,C_ID_92a2005557,69,N,0,A,278,M_ID_35d5f43c28,-7,-0.431922,2017-07-15 14:58:36,1.0,9,37
12455126,Y,C_ID_92a2005557,69,N,0,A,560,M_ID_b3c49066d8,-7,-0.694631,2017-07-22 10:09:40,1.0,9,34
12455127,Y,C_ID_92a2005557,69,N,0,A,561,M_ID_50f575c681,-2,-0.725465,2017-12-26 14:14:42,1.0,9,7
12455128,Y,C_ID_92a2005557,69,N,0,A,309,M_ID_b790230ee9,-2,-0.553066,2017-12-14 12:59:55,1.0,9,21
12455129,Y,C_ID_92a2005557,69,N,0,A,818,M_ID_b66f23e4da,-2,-0.634209,2017-12-24 10:30:34,1.0,9,12
12455130,N,C_ID_92a2005557,69,N,0,A,278,M_ID_35d5f43c28,-7,-0.431922,2017-07-15 14:58:10,1.0,9,37
12455131,Y,C_ID_92a2005557,69,N,0,A,526,M_ID_03bb6f5a3b,-1,-0.446378,2018-01-15 16:33:42,1.0,9,25

In [126]:
historical_transactions.loc[historical_transactions['card_id'] == 'C_ID_92a2005557'].city_id.count()

authorized_flag         260
card_id                 260
city_id                 260
category_1              260
installments            260
category_3              260
merchant_category_id    260
merchant_id             254
month_lag               260
purchase_amount         260
purchase_date           260
category_2              260
state_id                260
subsector_id            260
dtype: int64

## Saving all extra features to a new .csv file

In [ ]:
data.to_csv('all/train_extra_features.csv', index = False)
testdata.to_csv('all/test_extra_features.csv', index = False)

# [Errno 13] Permission denied: 'submissions/submission_v0-001.csv'
#        means that the file is still opened somewhere